version: "3"
services:
  app:
    image: luisalejandro/frontdesk:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/frontdesk/app
      - ~/Library/Caches/Yarn:/home/frontdesk/.cache/yarn
    env_file:
      - .env