on:
  script:
    run: |
      const crypto = require("crypto");
      const id = crypto.randomBytes(16).toString("hex");
      return [{id}]
    every: 0 8 * * *

jobs:
  moviebox:
    runs-on: ubuntu-22.04
    steps:
      - uses: LuisAlejandro/movie-box@develop
        env:
          GH_TOKEN: ${{ secrets.GIST_PERSONAL_ACCESS_TOKEN }}
          GIST_ID: ${{ secrets.MOVIEBOX_GIST_ID }}
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          MOVIE_BOX_MODE: ${{ secrets.MOVIE_BOX_MODE }}
