on:
  rss:
    url: https://github.com/LuisAlejandro/agoras/releases.atom
    config:
      limit: 1

jobs:
  twitter-new-post:
    name: New Agoras version to Twitter
    runs-on: ubuntu-22.04
    steps:
      - uses: LuisAlejandro/agoras-actions@1.1.1
        id: twitter-post
        with:
          network: twitter
          action: post
          twitter-consumer-key: ${{ secrets.LD_TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.LD_TWITTER_CONSUMER_SECRET }}
          twitter-oauth-token: ${{ secrets.LD_TWITTER_OAUTH_TOKEN }}
          twitter-oauth-secret: ${{ secrets.LD_TWITTER_OAUTH_SECRET }}
          status-text: "${{ on.rss.outputs.title }}: A new version of #agoras has been released! ${{ on.rss.outputs.link }}"
          status-image-url-1: https://repository-images.githubusercontent.com/496808130/7aeca3c5-a610-4707-8c47-f2867af04a7d

      - uses: LuisAlejandro/agoras-actions@1.1.1
        with:
          network: twitter
          action: post
          twitter-consumer-key: ${{ secrets.LA_TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.LA_TWITTER_CONSUMER_SECRET }}
          twitter-oauth-token: ${{ secrets.LA_TWITTER_OAUTH_TOKEN }}
          twitter-oauth-secret: ${{ secrets.LA_TWITTER_OAUTH_SECRET }}
          status-text: "https://twitter.com/LuisDevelops/status/${{ steps.twitter-post.outputs.result }}"


  facebook-page-new-post:
    name: New Agoras version to Facebook
    runs-on: ubuntu-22.04
    steps:
      - uses: LuisAlejandro/agoras-actions@1.1.1
        id: facebook-post
        with:
          network: facebook
          action: post
          facebook-access-token: ${{ secrets.LD_FACEBOOK_ACCESS_TOKEN }}
          facebook-object-id: ${{ secrets.LD_FACEBOOK_OBJECT_ID }}
          status-text: "${{ on.rss.outputs.title }}: A new version of #agoras has been released! ${{ on.rss.outputs.link }}"
          status-image-url-1: https://repository-images.githubusercontent.com/496808130/7aeca3c5-a610-4707-8c47-f2867af04a7d


  linkedin-page-new-post:
    name: New Agoras version to LinkedIn
    runs-on: ubuntu-22.04
    steps:
      - uses: LuisAlejandro/agoras-actions@1.1.1
        id: linkedin-post
        with:
          network: linkedin
          action: post
          linkedin-access-token: ${{ secrets.LA_LINKEDIN_ACCESS_TOKEN }}
          status-text: "${{ on.rss.outputs.title }}: A new version of #agoras has been released! ${{ on.rss.outputs.link }}"
          status-image-url-1: https://repository-images.githubusercontent.com/496808130/7aeca3c5-a610-4707-8c47-f2867af04a7d


  instagram-page-new-post:
    name: New Agoras version to LinkedIn
    runs-on: ubuntu-22.04
    steps:
      - uses: LuisAlejandro/agoras-actions@1.1.1
        with:
          network: instagram
          action: post
          instagram-access-token: ${{ secrets.LD_INSTAGRAM_ACCESS_TOKEN }}
          instagram-object-id: ${{ secrets.LD_INSTAGRAM_OBJECT_ID }}
          status-text: "${{ on.rss.outputs.title }}: A new version of #agoras has been released! ${{ on.rss.outputs.link }}"
          status-image-url-1: https://repository-images.githubusercontent.com/496808130/7aeca3c5-a610-4707-8c47-f2867af04a7d
