name: Update Music Box gist

on:
  schedule:
    - cron: 0 8 * * *

jobs:
  musicbox:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jacc/music-box
      - run: npm install
      - uses: ./
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_API_KEY }}
          GH_TOKEN: ${{ secrets.GIST_PERSONAL_ACCESS_TOKEN }}
          LFMUSERNAME: ${{ secrets.LASTFM_USERNAME }}
          GIST_ID: ${{ secrets.MUSICBOX_GIST_ID }}
