name: Update Waka Box gist

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  wakabox:
    runs-on: ubuntu-22.04
    steps:
      - uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GIST_PERSONAL_ACCESS_TOKEN }}
          GIST_ID: ${{ secrets.WAKABOX_GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
