name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: build
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.PERSONAL_ACCESS_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: Wandalen/wretry.action@v1.4.8
        with:
          action: actions/github-script@v7
          with: |
            github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.PERSONAL_ACCESS_TOKEN }}"
            script: |
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              })
          attempt_limit: 3
          attempt_delay: 2000