name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Restoring node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Set environment variable
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV
          touch .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Building docker image
        uses: docker/build-push-action@v3
        with:
            tags: luisalejandro/actionsflow-workflow:latest
            file: Dockerfile
            context: .
            build-args: |
                UID=${{ env.UID }}
                GID=${{ env.GID }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            push: false
            load: true

      - name: Building project
        run: |
          make dependencies build clean

  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: build
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@v6
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
